### PR TITLE
feature: input validation for UUID and API KEY

### LINKED ISSUE #39: Form validation when users input UUID and API key
When we click load user data it does not check whether the user has given any input or not it simply moves to show loading
We could show a warning to the user that the input field is empty and that they have to fill it

### PR DESCRIPTION
**Pull request by nibih**
closes #39

### CODE REVIEW

**Comment by ieahleen** [comment]
please make the button disabled if the inputs are not valid

**Comment by nibih** [comment]
button is now disabled and i added a red text at the bottom if id and api key is not valid

**Review by ieahleen — CHANGES_REQUESTED** [review]
Thank you! Are you able to resolve the merge conflicts?

**Comment by nibih** [comment]
sorry! conflict fixed i think

**Review by ieahleen — COMMENTED** [review]
Thank you for your contribution!

**Pull request merged**
