### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by onthegocode**
Adding Favicon to index.html

Closes #xxxxx

### CODE REVIEW

**Review by ieahleen — CHANGES_REQUESTED** [review]
please upload the favicon file into the repo

**Comment by onthegocode** [comment]
Oh yes, my mistake I will create another pull request for it.

**Comment by onthegocode** [comment]
I'm sorry still new to pull requests.

**Comment by ieahleen** [comment]
when changes are requested, do not close the pull request, update it by commiting more changes to the branch

**Comment by onthegocode** [comment]
Sorry for the trouble thank you for your understanding I believe I have committed the favicon now.

**Review by ieahleen — CHANGES_REQUESTED** [review]
can you please don't change the file formatting?

**Comment by onthegocode** [comment]
Good Morning ieahleen,

Which folder should I put the favicon in?

Ty

**Comment by ieahleen** [comment]
same folder as the html file would be fine

**Comment by onthegocode** [comment]
I noticed the file structure I had wasn't up to date so I cloned the project, and tested to see if the favicon is working but noticed the site style looks different than the live one. Just wanted to confirm before committing.
new

**Comment by ieahleen** [comment]
Yes, the live site is behind — the live site is on `production` branch.

**Comment by onthegocode** [comment]
okay will commit now

**Comment by ieahleen** [comment]
the pr marks that it has 17 files changed, I will do a little clean up so only two result as changed

**Comment by onthegocode** [comment]
Yes that would be great thank you. 🙂

**Comment by ieahleen** [comment]
Now the branch has no conflicts with the main branch, pelase remove the extra files

**Comment by onthegocode** [comment]
I'm sorry what files need to be removed? Also the changes for index.html seemed to delete the <link> element in the head thats needed for the favicon.

**Comment by ieahleen** [comment]
there are 16 files changed with this PR, there should be only 2
image

**Pull request closed without merging**
